#=========================================================================
# Custom Scripts -- init
#=========================================================================

name: custom-init

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - pre-init.tcl
  - add-endcaps-welltaps.tcl
  - floorplan.tcl
  - pin-assignments.tcl
  - edge-blockages.tcl

