name: glb_top

commands:
  - bash get_glb_top_outputs.sh

inputs:
  - design.v

outputs:
  - glb_top_tt.lib
  - glb_top_ff.lib
  - glb_top.lef
  - glb_top.gds
  - glb_top.vcs.v
  - glb_top.sdf
  - glb_top.lvs.v
  - glb_top.sram.spi

parameters:
  multicorner: True

postconditions:
  - assert File( 'outputs/glb_top_tt.lib' ) # must exist
  - assert File( 'outputs/glb_top.lef' ) # must exist
  - assert File( 'outputs/glb_top.gds' ) # must exist
  - assert File( 'outputs/glb_top.vcs.v' ) # must exist
  - assert File( 'outputs/glb_top.sdf' ) # must exist
  - assert File( 'outputs/glb_top.lvs.v' ) # must exist
  - assert File( 'outputs/glb_top.sram.spi' ) # must exist

