#=========================================================================
# Custom Scripts -- init
#=========================================================================

name: custom-init

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - pre-init.tcl
  - add-endcaps-welltaps.tcl
  - place-macros.tcl
  - dont-touch.tcl

